In [104]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
import joblib



In [105]:
from sklearn.datasets import load_iris

In [106]:
data = load_iris()

In [107]:

df = pd.DataFrame(data.data, columns=data.feature_names)


In [108]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [109]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [110]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [111]:
df['target']= data.target

In [112]:
df['target']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [113]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [114]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [115]:
df['target_names'] = df['target'].map({i:name for i, name in enumerate(data.target_names)})

In [116]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [118]:
df["target_names"].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [119]:
binary_df = df[df['target'] != 2]

In [120]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [121]:
x_binary = binary_df[['sepal length (cm)', 'sepal width (cm)',	'petal length (cm)', 'petal width (cm)']]

In [130]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [126]:
y_binary = binary_df['target']

In [127]:
x_train, x_test, y_train, y_test = train_test_split(x_binary, y_binary, test_size=.2)

In [131]:

x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.460000          3.103750           2.888750   
std             0.628561          0.465641           1.432268   
min             4.400000          2.000000           1.000000   
25%             5.000000          2.800000           1.500000   
50%             5.400000          3.100000           3.150000   
75%             5.825000          3.400000           4.300000   
max             6.900000          4.400000           5.000000   

       petal width (cm)  
count         80.000000  
mean           0.797500  
std            0.562988  
min            0.100000  
25%            0.200000  
50%            1.000000  
75%            1.300000  
max            1.800000

In [133]:
scaler = StandardScaler()
x_train =  scaler.fit_transform(x_train)

In [134]:
x_test = scaler.fit_transform(x_test)


In [135]:
x_train


array([[-0.57635053,  0.85634713, -1.04599358, -1.06799711],
       [ 1.98520737, -0.00810423,  1.06180205,  1.07693432],
       [ 1.02462316, -0.22421707,  1.20232175,  1.07693432],
       [ 0.70442842,  0.20800861,  1.34284146,  1.79191147],
       [-1.69703211, -0.22421707, -1.11625343, -1.06799711],
       [-0.7364479 , -2.38534549,  0.42946336,  0.36195718],
       [ 0.70442842, -0.22421707,  0.92128234,  1.25567861],
       [ 0.06403895, -1.08866844,  1.06180205,  0.71944575],
       [ 0.86452579,  0.64023429,  1.1320619 ,  1.43442289],
       [-1.69703211,  0.20800861, -1.11625343, -1.06799711],
       [ 0.86452579, -1.9531198 ,  0.78076263,  0.36195718],
       [-0.09605842,  1.7207985 , -0.83521402, -0.71050854],
       [ 0.38423369, -0.22421707,  0.92128234,  0.71944575],
       [ 1.50491527,  0.20800861,  1.1320619 ,  1.25567861],
       [ 1.98520737, -0.00810423,  1.27258161,  1.25567861],
       [-1.37683737, -0.00810423, -0.97573372, -1.06799711],
       [ 0.22413632, -0.

In [140]:
svm_binary = SVC(kernel='linear',C=1.0,probability=True)

In [141]:
svm_binary.fit(x_train,y_train)

SVC(kernel='linear', probability=True)

In [142]:
svm_binary.predict(x_test)

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [145]:
print("binary class classification report:\n", classification_report(y_test, svm_binary.predict(x_test)))

binary class classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [146]:
confusion_matrix(y_test, svm_binary.predict(x_test))

array([[11,  0],
       [ 0,  9]])

In [147]:
joblib.dump(svm_binary,"svm_binary.pkl")

['svm_binary.pkl']

In [148]:
x_muliti=  df[['sepal length (cm)', 'sepal width (cm)',	'petal length (cm)', 'petal width (cm)']]

In [149]:
x_muliti

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [150]:
y_multi= df["target"]

In [151]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [154]:
x_train_multi, x_test_multi, y_train_multi, y_test_multi = train_test_split(x_muliti,y_multi)

In [155]:
svm_multi = SVC(kernel="linear")

In [156]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(kernel='linear')

In [159]:
svm_multi.predict(x_test_multi)

array([0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 0, 2, 1, 0, 0, 0, 2,
       0, 2, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 1, 2, 0])

In [160]:
print("report for multi class svc \n", classification_report(y_test_multi, svm_multi.predict(x_test_multi)))

report for multi class svc 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        10

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [161]:
confusion_matrix(y_test_multi, svm_multi.predict(x_test_multi))

array([[12,  0,  0],
       [ 0, 16,  0],
       [ 0,  0, 10]])

In [162]:
joblib.dump(svm_multi, "svm_multi")

['svm_multi']

# Logistic Regression